name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install deps
        run: pnpm i

      - name: Update Git Submodule
        run: git submodule init && git submodule update

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Build
        run: pnpm build

      - name: publish
        run: pnpm pub
        env:
          NODE_AUTH_TOKEN: '${{secrets.NAME_GENIE_NPM_TOKEN}}'

      - name: Extract version from package
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v${{ steps.version.outputs.value }}
          release_name: Release v${{ steps.version.outputs.value }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.value, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.NAME_GENIE_TOKEN }}
